### ISSUE TITLE
Keyboard shortcut 

### ISSUE THREAD

**Issue by leety** [marius-sucan/Quick-Picto-Viewer#13]
in the latest version, mouse wheel scroll is bound to zoom level; however, in the help-keyboard-shortcuts.txt, mouse wheel scroll is bound to scroll through images (previous and next).

Questions:
Is there any way to edit the keyboard shortcut in the current version or change the function of the mouse wheel scroll back to scroll images in a folder?

**Comment by marius-sucan** [comment]
Hello!

Thank you for the message .

1. In Quick Picto Viewer , shortcuts are assigned contextually. If you are in the «custom zoom level» mode, the wheel is associated to zoom in/out. Switch by double-clicking in the middle of the viewport to «adapt images in view» and then you can use the wheel to navigate through images. Ctrl+Wheel always changes zoom level.
2. Based on your feedback, the next version will clarify this in the keyboard shortcuts help section. Thank you.
3. There is no way to customize keyboard shortcuts in Quick Picto Viewer . The keyboard shortcuts are assigned in modules-interface.ahk and are intercepted by the main thread which executes functions based on the user context and in-app conditions. In other words, it is not simple to change or add a keyboard shortcut, because one has to change code in multiple places and must ensure the shortcuts are modified/attributed based on the context of interest.

Best regards, Marius.
