### ISSUE TITLE
Deleting images: options are not applied

### ISSUE THREAD

**Issue by hoppfrosch** [marius-sucan/Quick-Picto-Viewer#5]
DESCRIPTION;
When deleting an image (pressing "DEL") a dialog box pops up, asking for conformation to delete the image. Within this dialog box a drop down menu is offered to determine the further behaviour when deleting more images.
The options are: 
- "Always prompt for delete" 
- "No longer prompt before file deletion in this session"
- "Never prompt before file delete"

"Always prompt before delete" is the default value on first deletion.

1.) I want to delete an image pressing "DEL"
2.)  dialog box pops up - with "Always prompt before delete" selected
3) I change to ""No longer prompt before file deletion in this session" within dropdown
4.) Button "Delete" is pressed
5.) The first image is deleted
6.) Deletion of second image, pressing "DEL"
7.) **dialog box pops up AGAIN** - with "Always prompt before delete" selected

EXPECTED BEHAVIOUR:

as step 7.) I would expect, that the image is deleted immediately, according configuration in step 3.)

QPV Version 5.0.1

**Comment by marius-sucan** [comment]
Hello!

Thank you . I will look into it.

I will release soon a version with this bug fix and for other regressions related to the viewport.

Best regards, Marius.

**Comment by marius-sucan** [comment]
As a side note. I just discovered I have to «Watch» my own repositories to get notifications when people post new Issues or Pull Requests. So, from now on, I should get instant notifications.... Apologies for not replying earlier.

**Comment by marius-sucan** [comment]
Hello!

After looking into the bug, i was unable to reproduce the bug.

1. Open images folder.
2. Press DELETE key, select «No longer prompt before file deletion in this session» from the drop-down list.
3. Click on Delete button.

RESULT: I no longer get any prompts in the session for subsequent «Delete» key presses. However.... If «Permanently delete file, do not move to recycle bin» is selected... the dropdown option is ignored, and you will be prompted again. Is this your case?

Version tested QPV v5.0.6 [released today]. The tests were performed repeatedly in Thumbnails list mode and in Image view mode.

Please tell me if this bug is reproducible each time. Please ensure the AHK file is saved as UTF-8 with BOM. If it is not, unwanted behaviours usually emerge.

Best regards, Marius.

**Comment by hoppfrosch** [comment]
> If «Permanently delete file, do not move to recycle bin» is selected... the dropdown option is ignored, and you will be prompted again. Is this your case?

Yes, indeed this is the case. Having "Permanently" enabled leads to the described behaviour. Not a real problem rather than an unexpected behaviour.

Sorry for the late reply - was very busy lately,

**Comment by marius-sucan** [comment]
Thank you for coming back to it.

The solution is to have that control disabled... To emphasize it's ignored. 

Best regards, Marius.
